export const FETCH_USER = "FETCH_USER";
export const FILTER_USERS = "FILTER_USERS";
export const FETCH_ALL_USERS = "FETCH_ALL_USERS";
export const FETCH_USER_POSTS = "FETCH_USER_POSTS";
export const SET_SEARCH_VALUE = "SET_SEARCH_VALUE";
export const SET_SORT_BY_VALUE = "SET_SORT_BY_VALUE";
